apiVersion: v1
kind: Pod
metadata:
  name: nginx
  # labels:
  #   env: sim
  annotations:
    simSpec: "[{\"seconds\":600,\"cpu\":\"500m\",\"memory\":\"500Mi\",\"nvidia.com/gpu\":1},{\"seconds\":1200,\"cpu\":\"2\",\"memory\":\"1Gi\",\"nvidia.com/gpu\":2}]"
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    beta.kubernetes.io/os: simulated
  tolerations:
  - key: "virtual-kubelet.io/provider"
    value: "sim"
    effect: "NoSchedule"
