apiVersion: v1
kind: Pod
metadata:
  name: nginx-sim
  # labels:
  #   env: sim
  annotations:
    simSpec: "[{\"seconds\":5,\"cpu\":\"1\",\"memory\":\"2Gi\",\"nvidia.com/gpu\":0},{\"seconds\":10,\"cpu\":\"2\",\"memory\":\"4Gi\",\"nvidia.com/gpu\":1}]"
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 1
        memory: 2Gi
        nvidia.com/gpu: 1
      limits:
        cpu: 2
        memory: 4Gi
        nvidia.com/gpu: 1
  nodeSelector:
    beta.kubernetes.io/os: simulated
  tolerations:
  - key: "virtual-kubelet.io/provider"
    value: "sim"
    effect: "NoSchedule"
